<?php
    $apikey = "rzp_test_R8d4XFJwLWyHd2";
?>
<?php
session_start();
include "connect.php";

$claim_id = intval($_GET['claim_id'] ?? 0);

$stmt = $conn->prepare("SELECT * FROM payments WHERE bookingId = ?");
$stmt->bind_param("i", $claim_id);
$stmt->execute();
$result = $stmt->get_result();


$query = "
    SELECT 
        b.bookingid AS bid, b.status, b.bookingdate As bdate,
        m.title AS movietitle, b.seats AS bseat
        t.name As tname, t.price AS tprice, t.Location AS tlocation
    FROM booking b
    JOIN movies m ON b.movieid = m.movieid
    JOIN theatre t ON b.theatreid = t.theatreid
    WHERE b.bookingid = :bookingid
";
$stmt1 = $pdo->prepare($query);
$stmt1->bindParam(':bookingid', $claim_id, PDO::PARAM_INT);
$stmt1->execute();
$booking = $stmt1->fetch(PDO::FETCH_ASSOC);

$cntSeat=count(explode(",",$booking['bseat']));


if ($claim = $result->fetch_assoc()) {
    // ✅ Correct field for bill
    $bill = $claim['price'] * $cntSeat;  
}
?>


<form action="" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $apikey; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo intval($claim['price'] * $cntSeat * 100); ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php echo 'OID'.rand(10,100).'END';?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="CineBook"
    data-description="Book Your Movie Ticket Online"
    data-image="🌱"
    data-prefill.name="<?php echo $_SESSION['name'];?>"
    data-prefill.userid="<?php echo $_SESSION['userid'];?>"
    data-prefill.role="<?php echo $_SESSION['role'];?>"
    data-theme.color="#3de240ff"
></script>



<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
